export const ontarioCities = [
    "Ajax",
    "Barrie",
    "Belleville",
    "Brampton",
    "Brantford",
    "Brockville",
    "Burlington",
    "Cambridge",
    "Cornwall",
    "Guelph",
    "Hamilton",
    "Kanata",
    "Kenora",
    "Kingston",
    "Kitchener",
    "London",
    "Markham",
    "Mississauga",
    "Niagara Falls",
    "Oakville",
    "Oshawa",
    "Ottawa",
    "Peterborough",
    "Pickering",
    "Richmond Hill",
    "Sault Ste. Marie",
    "St. Catharines",
    "St. Thomas",
    "Sudbury",
    "Thunder Bay",
    "Timmins",
    "Toronto",
    "Vaughan",
    "Waterloo",
    "Welland",
    "Whitby",
    "Windsor",
    "Woodstock",
  ];